from pathlib import Path
from typing import Protocol, Generator, Any

class FileStorage(Protocol):
    def model_file_path(self) -> Path: ...
    def sound_output_path(self) -> Path: ...
    def make_new_version_output_dir(self) -> Path: ...
    def parameters_output_path(self) -> Path: ...
    def training_file_paths(self, name: str) -> Generator[Path, None, None]: ...

    def training_data_cache_path(self) -> Path: ...

    def output_folder_base_path(self) -> Path: ...

class DictStorage(Protocol):
    def save_dict(self, params: dict[str, Any]): ...
    def load_dict(self) -> dict[str, Any]: ...